<h3>Change Password</h3>
<?php 
$basePath = $this->basePath();
$form = $this->form;
$form->prepare();
$form->setAttribute('action', $basePath . '/elements/login/change-password');
$form->setAttribute('method', 'POST');
echo $this->form()->openTag($form);
echo '<div class="control-group">';
foreach ($form as $element) {
	$attribs = $element->getAttributes();
	switch($attribs['type']) {
		case 'hidden':
			echo $this->formHidden($element);
			break;
			
		case 'submit':
			echo $this->formSubmit($element);
			break;
			
		default: 
			echo '<div class="control-group">';
			echo '<label id="'.$element->getName().'-label">
					<label for="'.$element->getName().'" class="control-label optional">'.$element->getLabel().'</label></label>';
			echo '<div class="controls">';
			echo $this->formElement($element);       // <-- Magic!
			// Set description if available
			$options = $element->getOptions();
			$description = (isset($options['description'])) ? $options['description'] : '';
			echo '<p class="hint">'.$description.'</p>';
			echo $this->formElementErrors($element);
			echo '</div>';
			echo '</div>';
			break;
	}
}
echo '</div>';
echo $this->form()->closeTag($form);
?>
<br />Form Data Submitted:
<pre>
<?php $this->escapeHtml(var_dump($data)); ?>
</pre>