<h3>Forgotten Password</h3>
<p>Please enter your account email below</p>
<?php 
$basePath = $this->basePath();
$form->prepare();
$form->setAttribute('action', $basePath . '/elements/login/forgot-password');
$form->setAttribute('method', 'POST');
$email = $form->get('email');
$submit = $form->get('submit')->setValue('Submit');
echo $this->form()->openTag($form);
?>
<table>
<tr><td><?php echo $this->formRow($email); ?></td></tr>
<tr><td><a href="/elements/login">Try logging in again</a></td></tr>
<tr><td><?php echo $this->formSubmit($submit); ?></td></tr>
<tr><td><?php echo $this->form()->closeTag($form); ?></td></tr>
</table>