<?php 
$basePath = $this->basePath();
$form->prepare();
$form->setAttribute('action', $basePath . '/elements/login');
$form->setAttribute('method', 'POST');
$email = $form->get('email');
$password = $form->get('password');
$submit = $form->get('submit');
?>

<link rel="stylesheet" type="text/css" href="<?php echo $this->basePath() . '/modules/elm-content/css/login-e3.css' ?>" />

<div class="content">
<?php if(count($flashMessages)) : ?>
<ul>
    <?php foreach ($flashMessages as $msg) : ?>
    <li><?php echo $msg; ?></li>
    <?php endforeach; ?>
</ul>
<?php endif; ?> 
  <div class="login-form">
    <h2><span><img src="<?php echo $this->basePath() . '/modules/elm-content/img/layout/icons/e3-icon.png'?>" alt="E3 Dashboard"></span> Login</h2>
    <?php echo $this->form()->openTag($form); ?>
      <fieldset>
        <div class="clearfix">
          <?php echo $this->formRow($email); ?>
        </div>
        <div class="clearfix">
          <?php echo $this->formRow($password); ?>
        </div>
        <?php echo $this->formSubmit($submit); ?>
        <div class="clearfix">
            <a href="/elements/login/forgot-password">Forgot password?</a>
        </div>
      </fieldset>
    <?php echo $this->form()->closeTag($form); ?>
  </div>
</div>