<?php 
echo $this->doctype();
// retrieve identity
use Zend\Authentication\AuthenticationService;
$authService = new AuthenticationService();
if ($authService->hasIdentity()) {
    $email = $authService->getIdentity()->email;
} else {
    $email = '';
}
$gravatar = '<span id="gravatar"><img src="'.$this->gravatar($email, "G", 25).'" width="25" height="25" /></span>';
?>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('ZF2 '. $this->translate('E3...'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/images/favicon.ico'))
                        ->prependStylesheet($this->basePath() . '/modules/elm-content/css/bootstrap-responsive.min.css')
                        ->prependStylesheet($this->basePath() . '/modules/elm-content/css/nav-e3.css')
                        ->prependStylesheet($this->basePath() . '/modules/elm-content/css/bootstrap.min.css')?>

        <!-- Scripts -->
        <?php echo $this->headScript()->prependFile($this->basePath() . '/modules/elm-content/js/html5.js', 'text/javascript', array('conditional' => 'lt IE 9',))
                                      ->prependFile($this->basePath() . '/modules/elm-content/js/bootstrap.min.js')
                                      ->prependFile($this->basePath() . '/modules/elm-content/js/jquery.min.js')
        ?>

    </head>
    <body>
        <header class="header">
          <div class="navbar navbar-inverse navbar-fixed-top">
            <div class="navbar-inner">
              <div class="container">
                <a class="brand" href="#"><img src="<?php echo $this->basePath() . '/modules/elm-content/img/layout/icons/e3-icon.png'?>" alt="E3 Dashboard"></a>
                <button type="button" class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                  <span class="elements-icon">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                  </span>
                  <span class="text">
                    Elements
                  </span>
                </button>
                <div class="nav-collapse collapse">
                  <ul class="nav">
                    <?php
                      echo $this->ElementsNavigation(); 
                    ?>
                  </ul>
                  <ul class="nav pull-right">
                    <!--li><a href="#">helpdesk</a></li>
                    <li><a href="#">settings</a></li-->
                    <li class="dropdown">
                      <a href="#" class="dropdown-toggle" data-toggle="dropdown"><?php echo $gravatar; ?> <b class="caret"></b></a>
                      <ul class="dropdown-menu">
                        <li><a href="/elements/login/change-password">Change password</a></li>
                        <li><a href="/elements/logout">Logout</a></li>
                      </ul>
                    </li>
                  </ul>
                </div><!--/.nav-collapse -->
              </div>
            </div>
          </div>
        </header>




        <div class="container">
        	<?php
            echo $this->content; 
            ?>
            <hr>
            <footer>
                <p>Elements &copy; Oxygenate Ltd <?php echo date('Y',time())?></p>
            </footer>
        </div> <!-- /container -->
        <?php echo $this->inlineScript() ?>
        <script src="<?php echo $this->basePath() . '/modules/elm-content/js/waypoints.min.js'?>"></script>
        <script src="<?php echo $this->basePath() . '/modules/elm-content/js/waypoints-sticky.js'?>"></script>
        <script type="text/javascript">
          (function($) {
            //$('.dropdown-toggle').dropdown();  
            $('[data-toggle="tooltip"]').tooltip({
              placement : 'top',
              trigger : 'hover',
              container : $(this).parent('td')
            });
            $('.sticky-element').waypoint('sticky', {
              offset: 45 // Apply "stuck" when element 40px from top
            });
          })(jQuery);
        </script>
    </body>
</html>
